services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nubbly_backend
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_started
    ports:
      - "3000:3000"
    networks:
      - nub_network
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:3000
    networks:
      - nub_network
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - nub_network
    restart: always

networks:
  nub_network:
    driver: bridge
